### ISSUE TITLE
Unable to create an event

### ISSUE THREAD

**Issue by JoelRussell** [danielroy96/ussu-pims#21]
When I log in as 'Joel'
And I click 'Manage events'
And I click 'Create a new job'
And I enter 'StagTV test' into the 'Event name' field
And I enter '105HA00' into the 'Venue' field
And I select 'StagTV' from the 'Client' dropdown
And I ender 'test' into the 'Description' field
And I select 18/01/2019 14:00 in the 'Event start date' picker
And I select 19/01/2019 14:00 in the 'Event end date' picker
And I click 'Create event'

...nothing happens.

**Comment by danielroy96** [comment]
Caused by a simple param casing typo therefore 400 bad request, easy fix
